module.exports = {
  theme: {
    extend: {
      colors: {
        primary: "#1E1E1E",
        secondary: "#F2F2F2",
        tertiary: "#F2F2F2",
        quaternary: "#F2F2F2",
        quinary: "#F2F2F2",
        senary: "#F2F2F2",
        septenary: "#F2F2F2",
        octonary: "#F2F2F2",
        nonary: "#F2F2F2",
        denary: "#F2F2F2",
        "primary-light": "#1E1E1E",
        "secondary-light": "#F2F2F2",
        "tertiary-light": "#F2F2F2",
        "quaternary-light": "#F2F2F2",
        "quinary-light": "#F2F2F2",
        "senary-light": "#F2F2F2",
        "septenary-light": "#F2F2F2",
        "octonary-light": "#F2F2F2",
        "primary-dark": "#1E1E1E",
        "secondary-dark": "#F2F2F2",
        "tertiary-dark": "#F2F2F2",
        "quaternary-dark": "#F2F2F2",
        "quinary-dark": "#F2F2F2",
        "senary-dark": "#F2F2F2",
        "primary-darker": "#1E1E1E",
        "secondary-darker": "#F2F2F2",
        "tertiary-darker": "#F2F2F2",
        "quaternary-darker": "#F2F2F2",
        "quinary-darker": "#F2F2F2",
        "senary-darker": "#F2F2F2",
        "septenary-darker": "#F2F2F2",
        "octonary-darker": "#F2F2F2",
        "nonary-darker": "#F2F2F2",
        "denary-darker": "#F2F2F2",
      },
    },
    fontSize: {
      sm: "12.8px",
      base: "16px",
      xl: "20px",
      "2xl": "24px",
      "3xl": "32px",
      "4xl": "40px",
      "5xl": "48px",
    },
  },
  plugins: [],
  content: ["./**/*.liquid"],
};
